In [1]:
import numpy as np

In [2]:
#matrix addition
A = np.array([[1, 2], [2, 3], [4, 5]])
B = np.array([[4, 1], [3, 6], [8, 2]])
C = A + B
print(C)

[[ 5  3]
 [ 5  9]
 [12  7]]


In [ ]:
#matrix subtraction
C = A - B

In [4]:
#matrix scalar multiplication
a = 3
C = a * A
print(C)

[[ 3  6]
 [ 6  9]
 [12 15]]


In [6]:
#matrix element multiplication
C = np.multiply(A, B)
print(C)

[[ 4  2]
 [ 6 18]
 [32 10]]


In [10]:
#matrix multiplication
A = np.array([[1, 2], [2, 3], [5, 6]])
B = np.array([[1, 2, 3], [4, 5, 6]])
C = np.matmul(A, B)
print(C)

[[ 9 12 15]
 [14 19 24]
 [29 40 51]]
